#if defined _logger_stocks_included
    #endinput
#endif
#define _logger_stocks_included

#include <amxconst>
#include <logger>
#include <logger_const>

/*******************************************************************************
 * STOCKS
 ******************************************************************************/

// native LoggerLogDebug(Logger:logger, const format[], any:...);
// native LoggerLogInfo(Logger:logger, const format[], any:...);
// native LoggerLogWarn(Logger:logger, const format[], any:...);
// native LoggerLogError(Logger:logger, const format[], any:...);